<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "event"
 *
 * Auto generated by Extension Builder 2013-09-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Event Management',
	'description' => 'Manage events in calendars.',
	'category' => 'plugin',
	'author' => 'Eike Starkmann',
	'author_email' => 'starkmann@undkonsorten.com',
	'author_company' => 'undkonsorten',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'addressmgmt' => '0.0.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>